TRUNCATE TABLE `poker_mission`;
INSERT INTO game.poker_mission(id, name, description, type, category, frequency, requirement_type, parameters, active) VALUES 
('1', 'Win x time any game', 'Win in any game', '1', '0', '30', '1', 'NULL', 'true'),
('2', 'Play x time with any game', 'Play in any game', '1', '0', '35', '2', 'NULL', 'true'),
('3', 'Exchange gold', 'Exchange Gold from oncase x times with any game - any value accepted', '1', '0', '35', '3', 'NULL', 'true'),
('4', 'Watch video ads', 'Watch videos ads x times with any game (Bixa, Holla, Xito, TienLen)', '1', '0', '900', '4', 'NULL', 'true'),
('5', 'Level up', 'Reach to x level (10, 20, 30, 40, 50...)', '2', '0', '0', '5', 'NULL', 'true'),
('6', 'Own gold', 'Own x amount of gold (1 mil, 5mil, 10 mil)', '2', '0', '0', '6', 'NULL', 'true'),
('7', 'Channel STREET win', 'Win at channel STREET', '2', '0', '0', '7', 'NULL', 'true'),
('8', 'Channel FREE win', 'Win at channel FREE', '2', '0', '0', '8', 'NULL', 'true'),
('9', 'Channel AMATUER win', 'Win at channel AMATUER', '2', '0', '0', '9', 'NULL', 'true'),
('10', 'Channel PRO win', 'Win at channel PRO', '2', '0', '0', '10', 'NULL', 'true'),
('11', 'Channel OPEN win', 'Win at channel OPEN', '2', '0', '0', '11', 'NULL', 'true'),
('12', 'Any channel win', 'Win at any channel', '2', '0', '0', '12', 'NULL', 'true'),
('13', 'Sending gift', 'Sending gift to x friends (5, 10, 15, 20...)', '2', '0', '0', '13', 'NULL', 'true'),
('14', 'Receiveing gift', 'Receiving gift from x friend (5, 10, 15, 20...)', '2', '0', '0', '14', 'NULL', 'true'),
('15', 'Making friend', 'Making x friends (50, 100...)', '2', '0', '0', '15', 'NULL', 'true'),
('16', 'Win 3 chi', 'Win 3 chi x competitor (5, 10, 15...)', '3', '1', '1000', '16', 'NULL', 'true'),
('17', 'Have Ace', 'Have Ace in x games', '3', '1', '1000', '17', 'NULL', 'true'),
('18', 'Win 3 chi', 'Mau Binh at x times (5, 10, 15...)', '3', '1', '1000', '18', 'NULL', 'true'),
('19', 'Holla Win 1st place', 'Win 1st place x times', '3', '2', '1000', '19', 'NULL', 'true'),
('20', 'Stolen card', 'Stolen card x times', '3', '2', '1000', '20', 'NULL', 'true'),
('21', 'Less than 10 pts', 'End the game with less than 10 points', '3', '2', '1000', '21', 'NULL', 'true'),
('22', 'Win 5 cards mode', 'Win x times in 5 cards mode', '3', '3', '1000', '22', 'NULL', 'true'),
('23', 'Win 7 cards mode', 'Win x times in 7 cards mode', '3', '3', '1000', '23', 'NULL', 'true'),
('24', 'All-in', 'All-in x time', '3', '3', '1000', '24', 'NULL', 'true'),
('25', 'Win game with 3 spade', 'Win the game with 3 spade (any game mode)', '3', '4', '1000', '25', 'NULL', 'true'),
('26', 'Booming', 'Booming x times (any game mode) - No need care about the game result', '3', '4', '1000', '26', 'NULL', 'true'),
('27', 'Win 1st place', 'Win 1st place x times', '3', '4', '1000', '27', 'NULL', 'true');
SELECT * FROM `poker_mission`;
